completed javascript-and-json
Blake-Frangoulis/c0523-code-solutions pull request #51
Opened 2023-05-26 18:32 UTC by Blake-Frangoulis

![image](https://github.com/Blake-Frangoulis/c0523-code-solutions/assets/130610365/45a3277f-fede-493c-8770-fb85b1b8588e)

2023-05-26 18:34 UTC, shawnkost requested changes
Missing a step here Blake!

2023-05-26 18:34 UTC, shawnkost commented on javascript-and-json/main.js
> +
You're missing a whole step where you're supposed to create a JSON string manually and log the value & typeof

2023-05-26 18:56 UTC, Blake-Frangoulis commented
![image](https://github.com/Blake-Frangoulis/c0523-code-solutions/assets/130610365/bdb45cc3-2859-41d1-9cef-5d3cddcf564b)

2023-06-05 17:52 UTC, shawnkost approved these changes
👍🏻

2023-06-06 16:48 UTC, merged